paths: # list or string
  - src/custommipmapsexport
#badge: docs # Path to save SVG file
exclude: .*/tests # regex
verbose: 3 # int (0-4)
skip_magic: True # Boolean
skip_file_doc: True # Boolean
skip_init: True # Boolean
skip_class_def: False # Boolean
skip_private: True # Boolean
follow_links: True # Boolean
accept_empty: True # Boolean
ignore_names_file: .*/tests # regex
fail_under: 25 # int
percentage_only: False # Boolean
ignore_patterns: # Dict with key/value pairs of file-pattern/node-pattern
  .*:
    - process
